config/routes.rb
Rails.application.routes.draw do
  post '/pages', to: 'pages#create'
  get '/searches', to: 'searches#index'


  root to: 'pages#index'
#  get 'contact', to: 'pages#contact'
  get '/pages/:id', to: 'pages#show', as: 'page'
  get '/gallery_types/:id', to: 'gallery_types#show', as: 'gallery_type'


  # resources :pages
  mount Ckeditor::Engine => '/ckeditor'
  resources :galleries
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '*path', to: 'pages#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/about.html.haml
.container
  %p
    广西南宁四方连续文化传播有限公司
    %br/
    四方连续 / 简介
    %br/
    广西南宁四方连续文化传播有限公司（简称：四方连续创享品牌 / The continuous），专注品牌形象量身定制，是一家注重实效的新锐设计公司，以品牌设计为核心业务，为各阶段企业提供务实的形象策划服务。
    %br/
    四方连续核心服务：品牌形象建立与升级：品牌策划 \ 标志设计 \ VIS设计 \ 商业空间设计； 推广物料设计：画册样本设计 \ 展会形象设计 \ 包装设计 \ 网站设计；广告设计代理：专业地产整合推广以及品牌形象年度设计管理。
    %br/
    四方连续是一个积极向上的年轻团队，我们怀着一颗进取、责任、感恩的心，致力服务于重视形象价值的客户，提供相互尊重与信任的设计服务，我们不只为了盈利，更怀揣着创想未来的梦想！
    %br/
    热忱期待与更多潜力型企业客户共同成长、携手同行。
  %h4 我们的原则
  .row.center-align.aboutus-row
    .col.l4.s12
      = image_tag("m/about_us/1484044990_Icon_Business_Set_00016_A.png", class: "responsive-img")
      %h5 策略 / Strategy
      %p 以品牌营销策略为目标的用户分析、内容信息构建及落地方式。
    .col.l4.s12
      = image_tag("m/about_us/1484045043_Experience_Project", class: "responsive-img")
      %h5 体验 / Experience
      %p 通过适合受众者的视觉设计方式来达到品牌与人之间的最佳用户体验。
    .col.l4.s12
      = image_tag("m/about_us/1484044958_5360_-_Dzone", class: "responsive-img")
      %h5 新锐 / Young
      %p 四方连续是一个积极向上的年轻团队，我们怀着一颗进取、责任、感恩的心，致力服务于重视形象价值的客户。

app/views/pages/contact.html.haml
%p
  contact haml
%h3.header= sanitize @page.title
%p= sanitize @page.body


%p wechat

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/find_us.haml
%p
  contact haml
%h3.header= sanitize @page.title
%p= sanitize @page.body


%script{"data-turbolinks-track" => "reload", :src => "http://api.map.baidu.com/api?v=2.0&ak=htvwHrLbN3yVDwvAEooFgBRkbv1MgHfG", :type => "text/javascript"}
  
// 百度地图容器
#map.col-xs-10.col-xs-offset-1{:style => "height:550px;border:#ccc solid 1px;color: #000;font-size:12px"} 


:javascript
  
  (function ($) {
  $(document).on('turbolinks:load', function() {
   
  //创建和初始化地图函数：
    function initMap(){
      createMap();//创建地图
      setMapEvent();//设置地图事件
      addMapControl();//向地图添加控件
      addMapOverlay();//向地图添加覆盖物
    }
    function createMap(){ 
      map = new BMap.Map("map"); 
      map.centerAndZoom(new BMap.Point(108.377773,22.816973),15);
    }
    function setMapEvent(){
      map.enableKeyboard();
      map.enableDragging();
      map.enableDoubleClickZoom()
    }map
    function addClickHandler(target,window){
      target.addEventListener("click",function(){
        target.openInfoWindow(window);
      });
    }
    function addMapOverlay(){
      var markers = [
        {content:"汇东国际E座18楼",title:"四方连续创意机构",imageOffset: {width:-46,height:-21},position:{lat:22.819105,lng:108.379713}}
      ];
      for(var index = 0; index < markers.length; index++ ){
        var point = new BMap.Point(markers[index].position.lng,markers[index].position.lat);
        var marker = new BMap.Marker(point,{icon:new BMap.Icon("http://api.map.baidu.com/lbsapi/createmap/images/icon.png",new BMap.Size(20,25),{
          imageOffset: new BMap.Size(markers[index].imageOffset.width,markers[index].imageOffset.height)
        })});
        var label = new BMap.Label(markers[index].title,{offset: new BMap.Size(25,5)});
        var opts = {
          width: 200,
          title: markers[index].title,
          enableMessage: false
        };
        var infoWindow = new BMap.InfoWindow(markers[index].content,opts);
        marker.setLabel(label);
        addClickHandler(marker,infoWindow);
        map.addOverlay(marker);
      };
    }
    //向地图添加控件
    function addMapControl(){
      var scaleControl = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
      scaleControl.setUnit(BMAP_UNIT_IMPERIAL);
      map.addControl(scaleControl);
      var navControl = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_LEFT,type:1});
      map.addControl(navControl);
      var overviewControl = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:false});
      map.addControl(overviewControl);
    }
    var map;
      initMap(); 
  
  
  }); // document ready  
  })(jQuery);

app/views/pages/index.html.haml
.row
  .index-slider-wrap
    .index-slider
      %h3 All Articles
      .index-slider-image
        %picture
          %source{ :media => "(max-width:768px)", :srcset => "#{asset_path('m/i1-1200-crop.jpg')}"}
          %source{ :media => "(min-width:768px)", :srcset => "#{asset_path('m/i1.jpg')}"}
          = image_tag "m/i1-1200-crop.jpg", :class => "responsive-img"
          / %img{src: "assets/m/i1.jpg"}

    .index-slider
      %h3 All Articles
      .index-slider-image
        %picture
          %source{ :media => "(max-width:768px)", :srcset => "#{asset_path('m/i4-1200-crop.jpg')}"}
          %source{ :media => "(min-width:768px)", :srcset => "#{asset_path('m/i4.jpg')}"}
          = image_tag "m/i4-1200-crop.jpg", :class => "responsive-img"


=render '/content_page'

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.haml
%p#notice= notice

.container
  %h3.header= sanitize @page.title
  %p= sanitize @page.body

app/views/pages/views.html.haml
-# %h3.header= sanitize @page.title
-# %p= sanitize @page.body


.views-page-container
  .views-slider-wrap.center-align.white-text
    .views-slider.first
      %h4 公司主要特点
      %h4 COMPANY'S MAIN CHARACTERISTICS
      %h3 只为壹个目的
      %p 
        我们所做的一切，只为一个目的，即:销售！
        %br
        广告首先是商业行为，而后才是艺术展现……      

    .views-slider.second
      %h4 公司主要特点
      %h4 COMPANY'S MAIN CHARACTERISTICS
      %h3 贰个基本认识
      %p 
        品牌市场营销的本质是什么？
        %br
        为客户创造价值，满足客户需求，在为客户创造价值的基础上，同时企业创造利润。
      %p 
        品牌推广的核心是什么？
        %br
        品牌推广的核心是--创意！

    .views-slider.third
      %h4 公司主要特点
      %h4 COMPANY'S MAIN CHARACTERISTICS
      %h3 坚持叁个原则
      %p 
        坚持从务实的角度去检验创意;
      %p 
        坚持以实效广告推动销售;
      %p
        坚持以消费心理洞察中寻找有效的传播、沟通方式！

    .views-slider.fourth
      %h4 公司主要特点
      %h4 COMPANY'S MAIN CHARACTERISTICS
      %h3 遵守肆大定律
      %p
        一、拒绝盲人摸象
        %br
        品牌的市场营销推广部是简单的概念包装+平面设计。
        %br
        需要在准确把握市场动态发展的前提下，对品牌、产品进行深度的解读：
        %br
        需要在对营销策略的充分理解的组合传播概念信息形成精准的传播策略，在这个过程中需要
        %br
        多角度、全方位的审视项目市场进入的每一个专业块面！
      %p 
        二、拒绝空谈品牌
        %br
        品牌，非一日之功！
        %br
        品牌的形成与完善需要多层面的构建与多角度的维护，
        %br
        品牌是棵树，树大好乘凉！
        %br
        树之茁壮，非一日之功，树之茂盛，则需要精心呵护，
      %p 
        三、拒绝本末倒置
        %br
        实效市场营销推广的标准，后先是围绕“销”来设计策略，
        %br
        当广告与营销相遇，关键是“营销”的“销”，并非“广告”的“广”，
        %br
        首先要“理解营销”才能“引导营销”才能更好的表现营销，
        %br
        最终为实现营销做贡献！
      %p
        四、选择适合的
        %br
        天马行空、奇思妙想的创意；
        %br
        高贵华丽、精美绝伦的画面表现；
        %br
        针对品牌、产品本身，选择适合的才是最好的。