config/routes.rb
Rails.application.routes.draw do
  post '/pages', to: 'pages#create'
  get '/searches', to: 'searches#index'


  root to: 'pages#index'
#  get 'contact', to: 'pages#contact'
  get '/pages/:id', to: 'pages#show', as: 'page'
  get '/gallery_types/:id', to: 'gallery_types#show', as: 'gallery_type'


  # resources :pages
  mount Ckeditor::Engine => '/ckeditor'
  resources :galleries
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '*path', to: 'pages#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_attached_file :cover, styles: { crop: "480x340#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/
    
  has_many :gallery_types, :through => :gallery_join_gallery_types
  has_many :gallery_join_gallery_types

  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :title, presence: true
  validates :cover, presence: true

  # elasticsearch =======================================
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  mappings dynamic: 'false' do
    indexes :id
    indexes :title, analyzer: "ik_max_word", search_analyzer: "ik_max_word", type: 'string'
    indexes :body, analyzer: "ik_max_word", search_analyzer: "ik_max_word", type: 'string'
  end

  def as_indexed_json(options={})
    self.as_json(
      include: { gallery_types: { }
               })
  end
  # ======================================================

  

end

app/models/gallery_type.rb
class GalleryType < ApplicationRecord
  has_many :galleries, :through => :gallery_join_gallery_types
  has_many :gallery_join_gallery_types
end

app/controllers/galleries_controller.rb
class GalleriesController < InheritedResources::Base
  before_action :find_all_galleries

  #  before_action :galleries_filter
  before_action :find_gallery, only: [:show]
  before_action :find_all_images, only: [:show]

  def index
    @galleries
    
  end

  def show
    @gallery
    @images

  end

  private

  def find_all_galleries
    query = params[:query].present? ? params[:query] : '*'
    #@galleries = Elasticsearch::Model.search( query, [Gallery] ).records
    @galleries = Array.new
    if params[:query]
      Gallery.order('id DESC').each do |g|
        g.gallery_types.each do |gt|
          @galleries << g if gt.name == params[:query]
        end
      end
    else
      @galleries = Gallery.order('id DESC')
    end
        
    
  end

  def find_gallery
    @gallery = Gallery.find(params[:id])
  end

  def find_all_images
    @images = @gallery.images.order('position ASC')
  end

  # def active_type?
  #   params[:query] 
  # end

  def gallery_params
    params.require(:gallery).permit(:title, :body, :side_body, :position, :photos)
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper


  # Acts as a thin wrapper for image_tag and generates an srcset attribute for regular image tags
  # for usage with responsive images polyfills like picturefill.js, supports asset pipeline path helpers.
  #
  # image_set_tag 'pic_1980.jpg', { 'pic_640.jpg' => '640w', 'pic_1024.jpg' => '1024w', 'pic_1980.jpg' => '1980w' }, sizes: '100vw', class: 'my-image'
  # 
  # => <img src="/assets/ants_1980.jpg" srcset="/assets/pic_640.jpg 640w, /assets/pic_1024.jpg 1024w, /assets/pic_1980.jpg 1980w" sizes="100vw" class="my-image">
  #
  def image_set_tag(source, srcset = {}, options = {})
    srcset = srcset.map { |src, size| "#{path_to_image(src)} #{size}" }.join(', ')
    image_tag(source, options.merge(srcset: srcset))
  end

  private
  
  def gallery_type_menus
    GalleryType.order('position ASC')
  end

end

app/views/galleries/_form.html.erb
<%= form_for(gallery) do |f| %>
  <% if gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :side_body %>
    <%= f.text_area :side_body %>
  </div>

  <div class="field">
    <%= f.label :position %>
    <%= f.number_field :position %>
  </div>

  <div class="field">
    <%= f.label :photos %>
    <%= f.text_field :photos %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Galleries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Side body</th>
      <th>Position</th>
      <th>Photos</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.title %></td>
        <td><%= gallery.body %></td>
        <td><%= gallery.side_body %></td>
        <td><%= gallery.position %></td>
        <td><%= gallery.images.first.image_file_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/galleries/index.html.haml
.row
  %section.col.l8.offset-l1.s12
    - @galleries.each do |gallery| 
      .col.l4.s6
        .project-cover.hoverable
          .cover-img
            = link_to (image_tag gallery.cover.url(:crop), class: 'responsive-img'), gallery_path(gallery)
            .project-title
              = link_to gallery_path(gallery) do
                %strong= gallery.title

          .project-taxonomy
            - gallery.gallery_types.each_with_index do |type, i|
              = link_to type.name, galleries_path(:query => type.name)
              = ", " unless gallery.gallery_types.length == i + 1

              
            /= type_array.join(", ").to_s
            / array.join(", ")
            / "," if type.last
            /=raise "oooo"


  %aside.col.l2.m6.s10
    /%h2= t('.other')
    .card.hoverable.sidebar
      = Pages::GalleryTypesMenuPresenter.new( gallery_type_menus, self).to_html
      /- byebug

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'form', gallery: @gallery %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gallery.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @gallery.body %>
</p>

<p>
  <strong>Side body:</strong>
  <%= @gallery.side_body %>
</p>

<p>
  <strong>Position:</strong>
  <%= @gallery.position %>
</p>

<p>
  <strong>Photos:</strong>
  <%= @gallery.photos %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.haml
.row
  %article.project-wrap.col.l8.offset-l1.s12
    #project-header
      #project-basic-info-wrap
        .project-title
          #project-name
            = @gallery.title
        .project-taxonomy
          - @gallery.gallery_types.each_with_index do |type, i|
            = link_to type.name, galleries_path(:gallery_type => type.name) 
            = ", " unless @gallery.gallery_types.length == i + 1

    .gallery-text
      %p
        = raw @gallery.body



    %section
      - @images.each do |i|
        .gallery-content-image= image_tag i.image.url(:thumb), srcset: "#{i.image.url(:w768)} 768w, #{i.image.url} 2000w",class: 'responsive-img'

  %aside.col.l2.m3.s12
    /%h2= t('.other')
    .card
      .card-content
        = content_tag(:span, @gallery.title, class: "card-title")

        %ul.menu.nav
          = Pages::GalleryTypesMenuPresenter.new( gallery_type_menus, self).to_html

      .card-action
        = content_tag(:span, "more", class: "card-title")
        %ul#galleries
          - if @gallery.position.present?
            - position = @gallery.position
            - if @galleries[position..position+5].length != 0
              - @galleries[position..position+5].each do |gallery| 
                %li
                  = link_to gallery.title, refinery.galleries_gallery_path(gallery)